#!/usr/bin/python
import ldapAccount
import sys
import optparse
import getpass

def usage(argv):
    cmd = argv[0]
    print 'Usage: ' + cmd + ' [populate | user | group | machine]'
    exit(1)

def main():
    args = sys.argv
    if len(args) < 2:
        usage(args)

    command  = args[1]
    commands = { 'populate': ldapAccount.do_population,
                 'user'    : ldapAccount.manage_user,
                 'group'   : ldapAccount.manage_group,
                 'machine' : ldapAccount.manage_machine }

    try:
        commands[command.lower()](args)
    except KeyError, e:
        print 'Unknown action: ', e
        usage(args)

if __name__ == '__main__':
    main()
